# SPDX-License-Identifier: PMPL-1.0-or-later
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: formdb-http-api
  labels:
    app: formdb-http-api
spec:
  minAvailable: 2  # Always keep at least 2 pods running
  selector:
    matchLabels:
      app: formdb-http-api
